import type { Metadata } from "next";
import Image from "next/image";
import { getTranslations } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { FaqSection } from "@/components/FaqSection";

const BASE = process.env.NEXT_PUBLIC_STOREFRONT_URL ?? "https://webshop.wsp-solarenergie.de";

type Props = { params: { locale: string } };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const t = await getTranslations({ locale: params.locale, namespace: "hybrid_solar_wind" });
  const isDE = params.locale === "de";
  const localePrefix = isDE ? "" : `/${params.locale}`;
  const canonicalUrl = `${BASE}${localePrefix}/hybrid-solar-wind-system`;

  const title = t("meta_title");
  const description = t("meta_desc");

  return {
    title,
    description,
    alternates: {
      canonical: canonicalUrl,
      languages: {
        "x-default": `${BASE}/hybrid-solar-wind-system`,
        de: `${BASE}/hybrid-solar-wind-system`,
        en: `${BASE}/en/hybrid-solar-wind-system`,
        es: `${BASE}/es/hybrid-solar-wind-system`,
      },
    },
    openGraph: {
      title,
      description,
      url: canonicalUrl,
      siteName: "Solarzaun & SkyWind – WSP Solarenergie",
      type: "website",
      images: [{ url: `${BASE}/images/skywind-hero.png`, width: 1200, height: 630, alt: "Hybrid solar wind system combining SkyWind NG turbine with solar panels" }],
    },
    twitter: { card: "summary_large_image", title, description },
  };
}

const FAQ_ITEMS = [
  {
    q: "What is a hybrid solar wind system?",
    a: "A hybrid solar wind system combines photovoltaic solar panels with one or more wind turbines, typically alongside battery storage. Each technology compensates for the other's weaknesses: solar delivers most energy in summer and daytime; wind contributes more in winter, at night and on overcast days. Together they achieve far higher year-round self-sufficiency than either alone.",
  },
  {
    q: "What are the main components of a hybrid solar wind system?",
    a: "A typical hybrid system includes: one or more wind turbines (e.g. SkyWind NG 1kW or 2kW), solar panels (rooftop PV, solar fence or open-area modules), a battery storage system to store surplus energy, an inverter/charge controller to manage power flows, and an energy management controller to optimise the combined system output.",
  },
  {
    q: "How much self-sufficiency can I achieve with a hybrid solar wind system?",
    a: "Well-designed hybrid systems can achieve 70–90%+ self-sufficiency in many European locations — significantly higher than solar-only (typically 30–50%) or wind-only systems. The exact figure depends on your site's solar and wind resources, battery capacity and energy consumption patterns.",
  },
  {
    q: "Is a hybrid solar wind system more cost-effective than solar alone?",
    a: "For properties with good wind exposure, yes — a hybrid system delivers a better return than adding more solar capacity. The capital cost is higher than solar alone, but the higher year-round generation and greater self-sufficiency typically result in shorter payback periods, particularly as grid electricity prices rise.",
  },
  {
    q: "What is the difference between the kombiloesungen page and this page?",
    a: "Our Kombilösungen page covers our full portfolio of combined energy solutions in German, including solar fences, photovoltaics, SkyWind and storage. This page specifically addresses the hybrid solar wind system concept for international customers searching in English, with a focus on combining the SkyWind NG wind turbine with solar panels.",
  },
  {
    q: "Can I add a hybrid solar wind system to an existing PV installation?",
    a: "Yes — adding a SkyWind NG wind turbine to an existing solar PV system is one of the most popular upgrades. The turbine can share the existing inverter infrastructure or use its own dedicated inverter, depending on your system design. We assess compatibility with your existing installation before recommending a configuration.",
  },
  {
    q: "How does a hybrid system handle excess energy generation?",
    a: "Surplus electricity generated by your hybrid system can be: stored in a battery for later use, fed into the grid for export tariff payment, diverted to a water heater or other thermal storage, or a combination of the above. We design the energy management strategy to maximise your benefit based on local grid tariffs and your usage patterns.",
  },
];

export default async function HybridSolarWindSystemPage({ params }: Props) {
  const isDE = params.locale === "de";
  const localePrefix = isDE ? "" : `/${params.locale}`;
  const canonicalUrl = `${BASE}${localePrefix}/hybrid-solar-wind-system`;

  return (
    <main>
      {/* Schema: BreadcrumbList */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            itemListElement: [
              { "@type": "ListItem", position: 1, name: "Home", item: BASE },
              { "@type": "ListItem", position: 2, name: "Combined Solutions", item: `${BASE}/kombiloesungen` },
              { "@type": "ListItem", position: 3, name: "Hybrid Solar Wind System", item: canonicalUrl },
            ],
          }),
        }}
      />

      {/* Hero */}
      <section className="relative overflow-hidden min-h-[55vh] sm:min-h-[75vh] flex items-center">
        <Image
          src="/images/skywind-hero.png"
          alt="Hybrid solar wind system with SkyWind NG turbine and solar panels generating clean electricity"
          fill
          className="object-cover object-center"
          priority
          sizes="100vw"
        />
        <div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/60 to-black/20" />
        <div className="relative w-full">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-16 sm:pt-20">
            <nav className="flex items-center gap-2 text-xs text-white/60 mb-6">
              <Link href="/" className="hover:text-white transition-colors duration-150">Home</Link>
              <span>/</span>
              <Link href="/kombiloesungen" className="hover:text-white transition-colors duration-150">Combined Solutions</Link>
              <span>/</span>
              <span className="text-white/90">Hybrid Solar Wind System</span>
            </nav>
            <div className="max-w-2xl">
              <p className="text-xs font-medium text-brand-accent uppercase tracking-widest mb-4">
                SkyWind NG + Solar · Maximum Self-Sufficiency
              </p>
              <h1 className="font-display text-3xl sm:text-5xl font-bold text-white leading-tight mb-5">
                Hybrid Solar Wind System –<br />
                <span className="text-brand-accent">Maximum Energy Independence.</span>
              </h1>
              <p className="text-base sm:text-lg text-white/80 leading-relaxed mb-8 max-w-xl">
                A hybrid solar wind system combines photovoltaic solar panels with a SkyWind NG
                wind turbine to deliver clean electricity year-round. Solar covers summer peaks;
                wind covers winter lows. Together, they achieve self-sufficiency rates that
                neither technology can reach alone.
              </p>
              <div className="flex flex-col sm:flex-row gap-3">
                <Link
                  href="/kontakt"
                  className="inline-block bg-brand-accent text-white font-semibold px-8 py-3 rounded-xl hover:bg-green-600 transition-colors duration-150 text-center"
                >
                  Design My Hybrid System
                </Link>
                <Link
                  href="/kombiloesungen"
                  className="inline-block border border-white/40 text-white font-semibold px-8 py-3 rounded-xl hover:border-white hover:bg-white/10 transition-colors duration-150 text-center"
                >
                  Combined Solutions Overview
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Why Hybrid */}
      <section className="py-16 sm:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <p className="text-xs font-medium text-brand-accent uppercase tracking-widest mb-3">The Case for Hybrid</p>
              <h2 className="font-display text-3xl sm:text-4xl font-bold text-gray-900 mb-6">
                Why Solar and Wind Work Better Together
              </h2>
              <p className="text-gray-600 leading-relaxed mb-4">
                Solar panels and wind turbines have naturally complementary generation profiles.
                Solar excels on long summer days with clear skies — exactly when wind speeds
                are often lower. Wind turbines perform best in autumn and winter — precisely
                when solar panels produce less energy.
              </p>
              <p className="text-gray-600 leading-relaxed mb-4">
                This seasonal complementarity means a hybrid system generates electricity more
                evenly throughout the year. Add battery storage and the combination covers the
                gaps that neither technology can fill alone — cloudy winter days, calm summer
                evenings, and everything in between.
              </p>
              <p className="text-gray-600 leading-relaxed mb-6">
                Research consistently shows that hybrid solar-wind systems achieve significantly
                higher self-sufficiency rates than single-source systems at the same total
                installed capacity. For homeowners and businesses serious about energy
                independence, the hybrid approach is the rational choice.
              </p>
              <div className="grid grid-cols-3 gap-4">
                {[
                  { value: "70–90%", label: "Self-sufficiency achievable" },
                  { value: "12 months", label: "Year-round generation" },
                  { value: "1 system", label: "One integrated solution" },
                ].map((m) => (
                  <div key={m.label} className="text-center bg-gray-50 rounded-xl p-4">
                    <div className="font-display text-xl font-bold text-brand-accent">{m.value}</div>
                    <div className="text-xs text-gray-600 mt-1">{m.label}</div>
                  </div>
                ))}
              </div>
            </div>
            <div className="relative aspect-[4/3] rounded-2xl overflow-hidden">
              <Image
                src="/images/skywind-hero.png"
                alt="Hybrid solar wind system installation combining SkyWind NG turbine with solar fence and rooftop PV panels"
                fill
                className="object-cover"
                sizes="(max-width: 1024px) 100vw, 50vw"
              />
            </div>
          </div>
        </div>
      </section>

      {/* System Components */}
      <section className="py-16 sm:py-24 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-xs font-medium text-brand-accent uppercase tracking-widest mb-3">Components</p>
            <h2 className="font-display text-3xl sm:text-4xl font-bold text-gray-900">
              Building Your Hybrid Solar Wind System
            </h2>
            <p className="text-gray-500 mt-4 max-w-2xl mx-auto">
              Every hybrid system is tailored to the site, energy demand and budget. Here are
              the key building blocks we work with.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              {
                title: "SkyWind NG Wind Turbine",
                desc: "The core wind generation unit. Available in 1kW and 2kW versions, compact enough for residential and commercial rooftops or freestanding masts.",
                link: { href: "/skywind-ng", label: "View SkyWind NG →" },
              },
              {
                title: "Solar Fence / PV Panels",
                desc: "Photovoltaic generation from a solar fence along your property boundary or conventional rooftop panels. The solar fence uniquely combines fencing with energy generation.",
                link: { href: "/solarzaun", label: "View Solar Fence →" },
              },
              {
                title: "Battery Storage",
                desc: "Stores surplus wind and solar energy for use whenever needed — at night, during calm spells or when demand peaks. Sized to your consumption and desired autonomy days.",
                link: null,
              },
              {
                title: "Hybrid Inverter",
                desc: "Manages power flow between wind, solar, battery and grid. Ensures maximum self-consumption and intelligent switching between sources for continuous supply.",
                link: null,
              },
            ].map((c) => (
              <div key={c.title} className="bg-white rounded-2xl p-6 border border-gray-100 flex flex-col">
                <h3 className="font-semibold text-gray-900 mb-2">{c.title}</h3>
                <p className="text-sm text-gray-600 leading-relaxed flex-grow">{c.desc}</p>
                {c.link && (
                  <Link href={c.link.href} className="mt-4 text-xs font-semibold text-brand-accent hover:underline">
                    {c.link.label}
                  </Link>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Seasonal Generation */}
      <section className="py-16 sm:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-xs font-medium text-brand-accent uppercase tracking-widest mb-3">Year-Round Performance</p>
            <h2 className="font-display text-3xl sm:text-4xl font-bold text-gray-900">
              How Solar and Wind Complement Each Other
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 gap-6 max-w-4xl mx-auto">
            {[
              {
                season: "Spring",
                solar: "High",
                wind: "Moderate",
                desc: "Rising solar production with spring storms boosting wind output. Battery fills quickly and system often exports surplus.",
              },
              {
                season: "Summer",
                solar: "Peak",
                wind: "Lower",
                desc: "Solar dominates. Long daylight hours and strong sun deliver maximum PV output. Wind contributes on overcast days.",
              },
              {
                season: "Autumn",
                solar: "Moderate",
                wind: "High",
                desc: "Wind generation rises as solar output begins to decline. The hybrid system maintains strong combined output.",
              },
              {
                season: "Winter",
                solar: "Low",
                wind: "Peak",
                desc: "Wind reaches its highest output. Without a turbine, winter is when solar-only systems struggle most. The hybrid fills this critical gap.",
              },
            ].map((s) => (
              <div key={s.season} className="border border-gray-100 rounded-2xl p-6">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-semibold text-gray-900">{s.season}</h3>
                  <div className="flex gap-3 text-xs">
                    <span className="bg-yellow-50 text-yellow-700 px-2 py-0.5 rounded-full">☀ Solar: {s.solar}</span>
                    <span className="bg-blue-50 text-blue-700 px-2 py-0.5 rounded-full">💨 Wind: {s.wind}</span>
                  </div>
                </div>
                <p className="text-sm text-gray-600 leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Planning */}
      <section className="py-16 sm:py-24 bg-gray-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-xs font-medium text-brand-accent uppercase tracking-widest mb-3">System Design</p>
            <h2 className="font-display text-3xl sm:text-4xl font-bold">
              From Idea to Working Hybrid System
            </h2>
            <p className="text-white/60 mt-4 max-w-2xl mx-auto">
              Every hybrid system is different. We start with your specific site, energy goals
              and budget — and build a system that truly works.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { step: "01", title: "Site & Resource Analysis", text: "We assess solar irradiance, wind data, roof structure and available ground area." },
              { step: "02", title: "Energy Demand Review", text: "We analyse your consumption to size the system correctly for your actual needs." },
              { step: "03", title: "System Design", text: "We select and size wind turbine, solar panels, battery and inverter components." },
              { step: "04", title: "Installation & Handover", text: "Certified partners install, commission and hand over your complete hybrid system." },
            ].map((s) => (
              <div key={s.step} className="bg-white/5 border border-white/10 rounded-xl p-5">
                <div className="font-display text-3xl font-bold text-white/20 mb-2">{s.step}</div>
                <div className="font-semibold text-white mb-1">{s.title}</div>
                <div className="text-sm text-white/60">{s.text}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <FaqSection items={FAQ_ITEMS} title="Hybrid Solar Wind System – Questions Answered" bg="white" />

      {/* Internal Links */}
      <section className="py-12 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="font-display text-xl font-bold text-gray-900 mb-6">Explore the System Components</h2>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {[
              { href: "/skywind-ng", label: "SkyWind NG Wind Turbine", desc: "Specs, pricing and ordering" },
              { href: "/solarzaun", label: "Solar Fence", desc: "Integrated fencing and PV generation" },
              { href: "/off-grid-wind-turbine", label: "Off-Grid Wind Systems", desc: "Battery-based energy independence" },
              { href: "/kombiloesungen", label: "Kombilösungen", desc: "German-language combined systems page" },
            ].map((l) => (
              <Link key={l.href} href={l.href} className="bg-white border border-gray-100 rounded-xl p-4 hover:border-brand-accent hover:shadow-sm transition-all duration-150">
                <div className="font-semibold text-gray-900 text-sm mb-1">{l.label}</div>
                <div className="text-xs text-gray-500">{l.desc}</div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 sm:py-20 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-xs font-medium text-brand-accent uppercase tracking-widest mb-3">Next Step</p>
          <h2 className="font-display text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
            Design Your Hybrid Solar Wind System
          </h2>
          <p className="text-gray-500 leading-relaxed mb-8">
            Share your location, energy goals and existing setup. We design a complete
            hybrid solar wind system tailored to your site — free of charge and with
            no obligation to proceed.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/kontakt" className="inline-block bg-brand-accent text-white font-semibold px-8 py-3 rounded-xl hover:bg-green-600 transition-colors duration-150">
              Request Free System Design
            </Link>
            <Link href="/products" className="inline-block border border-gray-200 text-gray-900 font-semibold px-8 py-3 rounded-xl hover:border-gray-400 transition-colors duration-150">
              Browse All Products →
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
